2023-07-05 18:10:21.542 [info] Experiment 'pythonaa' is active
2023-07-05 18:10:21.542 [info] Experiment 'pythonPromptNewFormatterExt' is active
2023-07-05 18:10:21.542 [info] Experiment 'pythonPromptNewToolsExt' is active
2023-07-05 18:10:21.542 [info] Experiment 'pythonSurveyNotification' is active
2023-07-05 18:10:21.542 [info] Test server listening.
2023-07-05 18:10:21.578 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2023-07-05 18:10:21.578 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2023-07-05 18:10:21.578 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2023-07-05 18:10:21.578 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2023-07-05 18:10:21.602 [info] > C:\Python311\python.exe -c "import sys;print(sys.executable)"
2023-07-05 18:10:21.643 [error] [Error: Command failed: C:\Python311\python.exe -c "import sys;print(sys.executable)"
/bin/sh: 1: C:Python311python.exe: not found

	at ChildProcess.exithandler (node:child_process:400:12)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1093:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'C:\\Python311\\python.exe -c "import sys;print(sys.executable)"'
}
2023-07-05 18:10:22.563 [info] Starting Pylance language server.
